config/routes.rb
Rails.application.routes.draw do
  resources :products do
      member do
        resources :items, only:[:create]
      end
  end
  resources :buyers, :products, :orders
  resources :items, :comments, :payments
  resources :sessions, only: [:new, :create, :destroy]

  root to: "static_pages#home"
  
  match '/signup', to: 'buyers#new', via: :get
  match '/signin', to: 'sessions#new', via: :get
  match 'signout', to: 'sessions#destroy', via: :delete

end

app/models/order.rb
class Order < ActiveRecord::Base
	attr_accessible :buyer_id, :status, :total_cost
	belongs_to :buyer
	has_many :items, dependent: :destroy

	before_save :create_remember_token2
	
	
	private 
		def create_remember_token2
			self.remember_token2 = SecureRandom.urlsafe_base64
		end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :sign_in_buyer
  before_filter :totalcost, only: [:show]
  
  def new
  end

  def create
    if create_order?
      flash[:warning] = "There is already existing an unpaid order!"
      redirect_to current_order
    else
      @unpaid_order = Order.new(buyer_id:current_buyer.id)
      @unpaid_order.status = "UnPaid"                      
      if @unpaid_order.save
        create_order @unpaid_order
        redirect_back_or_to current_order
      else
        flash[:warning] = "Order creates failure!"
        redirect_to current_buyer
      end
    end
  end

  def index
    redirect_to current_buyer
  end

  def edit
  end

  def update  
  end

  def show   
  end

  def destroy
    @order = current_buyer.orders.find_by_id(params[:id])
    @order.delete
    respond_to do |format|
      format.html {redirect_to current_buyer}
      format.js
    end
  end
  private 
      def totalcost
        @order = current_buyer.orders.find_by_id(params[:id])
        if !@order.nil?
            @order.total_cost = @order.items.sum(:product_price)
        else
          flash[:warning] = "This order is not existed or doesn't belong to you!"
          redirect_to current_buyer
        end
      end
end

app/helpers/orders_helper.rb
module OrdersHelper

	def create_order(order)
		cookies.permanent[:remember_token2] = order.remember_token2
		self.current_order = order
	end

	def create_order?
		return !current_order.nil?
	end

	def current_order=(order)
		@current_order = order
	end

	def current_order
		@current_order ||= Order.find_by_remember_token2(cookies[:remember_token2])
	end

	def delete_order
		self.current_order = nil
		cookies.delete(:remember_token2)
	end
	
	def cal_totalcost
        if create_order?
          self.current_order.total_cost = self.current_order.items.sum(:product_price)
        end
    end
	
	def store_url
		session[:return_to] = request.fullpath
	end

	def redirect_back_or_to (default)
		redirect_to session[:return_to] || default
		session.delete(:return_to)
	end 
end

app/views/orders/_order.html.erb
<table  class="table">
	<caption >Order: <%= order.id %>
		<%if !order.total_cost.nil? %>
			| Total Cost: $ <span id="order_cost"> <%= order.total_cost %> </span>
		<% end %>
	   | Status: <%= order.status %> | 
		<% if order.status == "UnPaid"%>
			<span id="paynow"> 
				<% if order.items.count > 0 %>
					<%= link_to "Pay Now", new_payment_path %>
				<% end %>
			</span>
		<% end %>
	</caption>
	<thread>
		<tr>
			<th>Item ID</th>
			<th>Product ID</th>
			<th>Product Name</th>
			<th>Product Price($)</th>
			<th>Operation</th>
		</tr>
	</thread>
	<tbody id="show_items">
	  <% if order.status == "UnPaid" %>
		   <%= render order.items %>
	  <% else %>
	  	<% order.items.each do |item| %>
	  		<tr class="active">
				<td> <%= link_to "#{item.id}", item %> </td>
				<td> <%= item.product_id %> </td>
				<td> <%= item.product_name %> </td>
				<td> <%= item.product_price %> </td>
				<% if item.commentable == true %>
					<td> <%= link_to "comment", item %> </td>
				<% else %>
					<td> <%= link_to "item detail", item %> </td>
				<% end %>
			</tr>
	  	<% end %>
	  <% end %>
	</tbody>
</table> 
<div><%= button_to "Delete", order, method: :delete,class: "btn btn-primary btn-sm", data: {confirm: "You sure?"}, remote: true %></div>

</br>

app/views/orders/create.js.erb
$("#buy").html("<%= escape_javascript(<% if sign_in? %>) %>")

app/views/orders/destroy.js.erb
$("#show_orders").html("<%= escape_javascript(render current_buyer.orders) %>")

app/views/orders/new.html.erb
<h1>New Order</h1>
	<div class="row">
		<%= form_for(@order) do |f| %>
			<p> Order: <%= @order_number %> </p>
			<%= f.submit "Create a order", class:"btn btn-large btn-primary" %>
		<% end %>
	</div>

app/views/orders/show.html.erb
<table  class="table">
  <caption >Order: <%= @order.id %> 
    <%if !@order.total_cost.nil? %>
      | Total Cost: $ <span id="order_cost"> <%= @order.total_cost %> </span>
    <% end %>
   | Status: <%= @order.status %> | 
    <% if @order.status == "UnPaid"%>
      <span id="paynow"> 
        <% if @order.items.count > 0 %>
          <%= link_to "Pay Now", new_payment_path %>
        <% end %>
      </span>
    <% end %>
  </caption>
  <thread>
    <tr>
      <th>Item ID</th>
      <th>Product ID</th>
      <th>Product Name</th>
      <th>Product Price($)</th>
      <th>Operation</th>
    </tr>
  </thread>
  <tbody id="show_items">
    <% if @order.status == "UnPaid" %>
       <%= render @order.items %>
    <% else %>
      <% @order.items.each do |item| %>
        <tr class="active">
        <td> <%= link_to "#{item.id}", item %> </td>
        <td> <%= item.product_id %> </td>
        <td> <%= item.product_name %> </td>
        <td> <%= item.product_price %> </td>
        <% if item.commentable == true %>
          <td> <%= link_to "comment", item %> </td>
        <% else %>
          <td> <%= link_to "item detail", item %> </td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table> 

<div>
	<% if @order.status == 'UnPaid' %>
		<% if @order.items.count > 0 %>
  			<div id="paynow" class="row">
  				<%= link_to "Pay Now", new_payment_path %>
  			</div>
  			<div class="row">
  				<%= link_to "Continue Shopping", root_url %>
  			</div>
  		<% else %>
  			<div id="paynow" class="row">
  				<%= link_to "Continue Shopping", root_url %>
  			</div>
  		<% end %>
	<% end %>
</div>