config/routes.rb
Rails.application.routes.draw do
  resources :products do
      member do
        resources :items, only:[:create]
      end
  end
  resources :buyers, :products, :orders
  resources :items, :comments, :payments
  resources :sessions, only: [:new, :create, :destroy]

  root to: "static_pages#home"
  
  match '/signup', to: 'buyers#new', via: :get
  match '/signin', to: 'sessions#new', via: :get
  match 'signout', to: 'sessions#destroy', via: :delete

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
	attr_accessible :name, :email, :password, :password_confirmation
	has_secure_password

	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token

	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\_.]+@[a-z\d\_.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
				uniqueness: {case_sensitive: false}
	validates :password, presence: true, length: {minimum: 6}
	validates :password_confirmation, presence: true

	has_many :orders, dependent: :destroy
	has_many :comments, dependent: :destroy
	
	private 
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessible :score, :buyer_id, :product_id, :item_id
	belongs_to :product
	belongs_to :buyer
	belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
	attr_accessible :product_id, :order_id, :product_name, :product_price, :commentable
	belongs_to :product
	belongs_to :order
	has_one :comment
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	attr_accessible :product_id, :order_id, :product_name, :product_cost
	validates :product_id, presence: true	
	belongs_to :product
	belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
	attr_accessible :buyer_id, :status, :total_cost
	belongs_to :buyer
	has_many :items, dependent: :destroy

	before_save :create_remember_token2
	
	
	private 
		def create_remember_token2
			self.remember_token2 = SecureRandom.urlsafe_base64
		end
end

app/models/product.rb
class Product < ActiveRecord::Base
	attr_accessible :title, :description, :image_url, :price
	has_many :items, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :sign_in_buyer

  def new
  end

  def create
    if create_order?
      @product = Product.find_by_id(params[:id])
      @item = Item.new(product_id:params[:id], order_id:current_order.id, product_name:@product.title, product_price:@product.price, commentable:true)
      if @item.save
        flash[:success] = "add #{@item.product_name}to shop cart successfully!"
        redirect_to current_order
      else
        render new_item_path
      end
    end
  end

  def destroy
      current_order.items.find_by_id(params[:id]).destroy
      current_order.total_cost = current_order.items.sum(:product_price)
      respond_to do |format|
          format.html {redirect_to current_order}
          format.js
      end
  end

  def show
    current_buyer.orders.each do |order|
        @item = order.items.find_by_id(params[:id])
        if !@item.nil?
            break
        end
    end
    if !@item.nil?
      @product = Product.find_by_id(@item.product_id)
      @comment = Comment.new(product_id:@product.id, buyer_id:current_buyer.id, item_id:params[:id])
    else
      flash[:warning] = "The item #{params[:id]} is not existed or doesn't belong to you!"
      redirect_to current_buyer
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def register
  end

  def login
  end

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

	def create_order(order)
		cookies.permanent[:remember_token2] = order.remember_token2
		self.current_order = order
	end

	def create_order?
		return !current_order.nil?
	end

	def current_order=(order)
		@current_order = order
	end

	def current_order
		@current_order ||= Order.find_by_remember_token2(cookies[:remember_token2])
	end

	def delete_order
		self.current_order = nil
		cookies.delete(:remember_token2)
	end
	
	def cal_totalcost
        if create_order?
          self.current_order.total_cost = self.current_order.items.sum(:product_price)
        end
    end
	
	def store_url
		session[:return_to] = request.fullpath
	end

	def redirect_back_or_to (default)
		redirect_to session[:return_to] || default
		session.delete(:return_to)
	end 
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(buyer)
		cookies.permanent[:remember_token] = buyer.remember_token
		self.current_buyer = buyer
	end

	def sign_in?
		return !current_buyer.nil?
	end

	def current_buyer=(buyer)
		@current_buyer = buyer
	end

	def current_buyer
		@current_buyer ||= Buyer.find_by_remember_token(cookies[:remember_token])
	end

	def sign_out
		self.current_buyer = nil
		cookies.delete(:remember_token)
	end

	def sign_in_buyer
		unless sign_in?
			redirect_to signin_path, notice: "please sign in first!"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer" >
	<nav>
		<ul class="nav pull-left ">
			<li > <%= link_to "XYZ's Github","https://github.com/xieyizun" %>
			</li>
		</ul>
		<ul class="nav pull-right">
			<li><%= link_to "About", "#" %></li>
			<li><%= link_to "Contact", "#" %></li>
			<li><a href="http://www.sysu.edu.cn/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div>
      <ul class="nav navbar-nav pull-left">
          <li> <%= link_to "Shopping World", '#', id: "logo" %> </li>
      </ul>
    </div>
    <div>
      <ul class="nav navbar-nav pull-right">
          <li><%= link_to 'Home', root_url %></li>
          <% if sign_in? %>
             <li id="fat-menu" class="dropdown">
                <a href='#' class="dropdown-toggle" data-toggle="dropdown" style="color: rgb(255,255,255)">
                  Account <b class="caret"></b>
                </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_buyer %></li>
                    <li><%= link_to "Settings", edit_buyer_path(current_buyer) %></li>
                    <li><%= link_to "Sign_out", signout_path, method: "delete" %></li>
                  </ul>
             </li>
             <li id="fat-menu" class="dropdown">
                <a href='#' class="dropdown-toggle" data-toggle="dropdown" style="color: rgb(255,255,255)">
                  Shop Cart <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Bought", buyer_path(current_buyer) %></li>
                  <% if create_order? %>
                      <li><%= link_to "Unpaid", order_path(current_order) %></li>
                  <% end %>
                </ul>
            </li> 
          <% else %>
            <li id="fat-menu" class="dropdown">
                <a href='#' class="dropdown-toggle" data-toggle="dropdown" style="color: rgb(255,255,255)">
                  Account <b class="caret"></b>
                </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Sign_in", signin_path %></li>
                    <li><%= link_to "Register", signup_path %></li>
                  </ul>
             </li>
          <% end %>    
        </ul>
      </nav>
    </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping World</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
   <%= render 'layouts/header' %>
   <div class="container">
    
      <% flash.each do |key, value| %>
         <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      
   	  <%= yield %>
      <%= render 'layouts/footer' %>
   </div>  
</body>
</html>

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
   <%= render 'shared/error_messages', object: f.object %>
   <div id="comment_area">
   	   <%= f.text_area :score %>
   </div>
</br>
   <%= f.submit "comment", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
  	<div class="alert alert-error">
  		The form contains <%= pluralize(object.errors.count, "error") %>.
  	</div>
  	<ul>
  		<% object.errors.full_messages.each do |msg| %>
  		   <li>* <%= msg %> </li>
  		<% end %>
  	</ul>
  </div>
<% end %>
 